language: python
sudo: required
python:
  - "3.7"

services:
  - postgresql

env:
  - DJANGO=2.1.7 DB=postgres
  - SECRET_KEY='test'
install:
  - pip wheel -r requirements.txt
   # Install the dependencies the app itself has
   # which in this case are kept in a requirements file
  - pip install -r requirements.txt
   # Install whatever version of Django that's listed above
   # Travis is currently working on
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: 
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test

